name: Build and publish a Docker image to ghcr.io
on:

  release:
    types: [ published ]

  push:
    branches:
      - master

jobs:
  publish:
    name: Build and push image to GHCR
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
